routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
});
Auth::routes();

//Route::get('users', ['uses'=>'UsersController@index']);
//Route::get('users/create', ['uses'=>'UsersController@create']);
//Route::post('users/create', ['uses'=>'UsersController@store']);
//Route::get('users/edit/{id}', ['uses'=>'UsersController@edit']);
//Route::put('users/edit/{id}', ['uses'=>'UsersController@update']);
//Route::delete('users/delete/{id}', ['uses'=>'UsersController@destroy']);
//'middleware' => ['auth', 'verified']]


Route::group(['namespace' => 'Backend', 'prefix' => 'console', 'middleware' => 'auth'], function () {

    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::resource('users', 'UsersController');
    });


    Route::resource('pages', 'PagesController');


    //Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::get('my-profile', ['as' => 'users.profile', 'uses' => 'UsersController@myProfile']);
    Route::post('my-profile', ['as' => 'users.profile.update', 'uses' => 'UsersController@updateMyProfile']);
    Route::get('my-profile/logs', ['as' => 'users.mylogs', 'uses' => 'UsersController@myLogs']);
    Route::get('my-profile/change-password', ['as' => 'users.profile.change.password', 'uses' => 'UsersController@changePassword']);
    Route::post('my-profile/update-password', ['as' => 'users.profile.update.password', 'uses' => 'UsersController@updateMyPassword']);
});


Route::group(['namespace' => 'Frontend'], function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::get('pages/comment', ['uses' => 'PagesCotroller@comment', 'as' => 'pages.comment']);
    });

    Route::get('pages', ['uses' => 'PagesCotroller@index', 'as' => 'pages.index']);
    Route::get('register', ['uses' => 'UsersCotroller@create']);
    Route::get('login', ['uses' => 'UsersCotroller@login']);

});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

//email notification

Route::get('/send-email',function(Illuminate\Http\Request $request){
    
    $details = [
        // 'subject'=>'email from Nexco Consultancy',
        // 'message'=>'We will contact you soon as possible.',
        // 'email' => $request ->get('email'),
        'subject' => $request -> get('subject'),
        'message' => $request -> get('message'),
    ];
    \Mail::to($request ->get('email'))->send(new \App\Mail\ContactMail($details));
    echo "Email has been Sent!";
});
Route::get('/contact', function () {
    return view('contact');
});

Route::get('/backend', 'ContactController@index');
Route::get('/show/{id}', 'ContactController@show');
Route::get('/reply/{id}', 'ContactController@reply');
Route::post('/save', 'ContactController@save');

Route::get('/form', function () {
    return view('emails.replyform');
});

Route::get('/sample', function () {
    return view('sample');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

use Plank\Metable\Metable;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use Metable;

    const ACTIVE = 1;
    const BANNED = 0;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'active', 'password', 'remember_token', 'email_verified_at'
    ];
    protected $appends = ['fullname'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
//    protected $casts = [
//        'email_verified_at' => 'datetime',
//    ];

    public function profile(){
        return $this->hasOne(Profile::class);
    }

    public function getFullnameAttribute()
    {
        if($this->profile())
        {
            return ucfirst($this->profile->display_name?$this->profile->display_name:$this->profile->full_name);
        }
        return ucfirst($this->username);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Page;
use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct(Page $page, User $user){
        $this->page=$page;
        $this->user=$user;
    }

    public function index(){
//        $pages= $this->page->published()->orderBy('view_count', 'DESC')->take(5)->get();
        $users = $this->user->latest('created_at')->take(5)->get();
        return view('backend.dashboard', compact( 'users'));
    }
}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        echo "hellp";
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SettingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use App\Page;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SettingsController extends Controller
{
    protected $settings,$page;
    public function __construct(Setting $setting, Page $page)
    {
        $this->setting = $setting;
        $this->page = $page;
    }

    public function index()
    {
        $pages = $this->page->all()->pluck('title','id')->toArray();
        return view('backend.settings.index', compact('pages'));
    }

    public function store(Request $request)
    {
        $rules = $this->setting->getValidationRules();
        $data = $this->validate($request, $rules);
        $validSettings = array_keys($rules);
        $tab_hash = $request->input('active_tab')?$request->input('active_tab'):null;
        foreach ($data as $key => $val) {
            if(in_array($key, $validSettings)) {
                $this->setting->add($key, $val, $this->setting->getDataType($key));
            }
        }
        return redirect()->route('settings.index')->with('success','Setting Successfully Saved')->with('tab_hash', $tab_hash);
    }
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Profile;
use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{
    protected $user, $profile;

    public function __construct(User $user, Profile $profile)
    {
        $this->user = $user;
        $this->profile = $profile;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = $this->user->paginate(20);
//        $roles = $this->role->all();
        $users = $this->user->all();
        return view('backend.users.index', compact('users'));
    }

    public function create()
    {
        $users = User::all();
        return view('backend.users.create', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
//    public function create()
//    {
//        return view('users.create');
//    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'username' => 'required|string|max:255|unique:users',
            'email' => 'required|string|email|max:255|unique:users',
            'full_name' => 'required|string|max:255',
            'password' => 'required|string|min:6|confirmed',
//            'role' =>'required'
        ]);
        $user_data = [
            'name' => $request->full_name,
            'username' => $request->username,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'status' => 1
        ];
//        dd($user_data);
        $profile_data = $request->only('full_name', 'nickname');
        $this->user->create($user_data);
//        $profile = new $this->profile($profile_data);
//        $user->profile()->save($profile);
//        $user->roles()->sync('');
        return redirect()->route('users.index')->with('success', 'User Created Successfully.');

    }

    //delete function
    public function destroy($id)
    {
        $user = $this->user->findorFail($id);
        $user->delete();
        return redirect()->back();
    }

    //edit function to redirect to edit view
    public function edit($id)
    {
        $user = $this->user->findorFail($id);
//        $roles = $this->role->all();
        return view('backend.users.edit', compact('user'));
    }

    //update function
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'full_name' => 'required|string|max:255',
            'nickname' => 'required|string|max:255',
//            'role' =>'required'
        ]);
        $profile_data = [
            'full_name' => $request->input('full_name'),
            'nickname' => $request->input('nickname'),
            'description' => $request->input('description'),
            'avatar' => $request->input('avatar'),
            'display_name' => $request->input('display_name'),
            'website' => $request->input('website'),
        ];
        $user = $this->user->findorFail($id);
        $user->profile->update($profile_data);
        // $user->roles()->sync($request->input('role'));
        return redirect()->route('users.index')->with('success', 'User Updated Successfully.');;
    }

    //change Password view
    public function changePassword()
    {
        $user = $this->user->findorFail(auth()->user()->id);
        return view('backend.users.change-password', compact('user'));
    }

    //update password
    public function updatePassword(Request $request, $id)
    {
        $this->validate($request, [
            'password' => 'required|string|min:6|confirmed',
        ]);
        $user = $this->user->findorFail($id);
        $user->update(['password' => bcrypt($request->password)]);
        return redirect()->route('users.index');
    }

    public function myProfile()
    {
        $user = auth()->user();
        return view('backend.users.my-profile', compact('user'));
    }

    public function updateMyProfile(Request $request)
    {
        $this->validate($request, [
            'full_name' => 'required|string|max:255',
            'nickname' => 'required|string|max:255',
        ]);
        $profile_data = [
            'full_name' => $request->input('full_name'),
            'nickname' => $request->input('nickname'),
            'description' => $request->input('description'),
            'avatar' => $request->input('avatar'),
            'display_name' => $request->input('display_name'),
            'website' => $request->input('website'),
        ];
        $user = auth()->user();
        $user->profile->update($profile_data);
        return redirect()->route('users.profile')->with('success', 'Profile Successfully Updated!');

    }

    public function updateMyPassword(Request $request)
    {
        $this->validate($request, [
            'password' => 'required|string|min:6|confirmed',
        ]);
        $user = auth()->user();
        $user->update(['password' => bcrypt($request->password)]);
        return redirect()->route('users.profile')->with('success', 'Password Successfully Updated!');

    }

    public function activateUser($id)
    {
        $user = $this->user->findOrFail($id);
        $user->status = User::ACTIVE;
        $user->save();
        return redirect()->back()->with('success', 'User Successfully Banned!!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
//    public function show($id)
//    {
//        $user = $this->modal->findOrFail($id);
////        return view('users.edit', compact($user));
//    }

}

resources/views/backend/users/create.blade.php
@extends('layout')

{{--@section('title', 'Create User')--}}

{{--@section('content')--}}
{{--    <form action="{{ route('users.store') }}" method="post">--}}
{{--        @csrf--}}
{{--        <input type="text" name="name" placeholder="Name"><br>--}}
{{--        <input type="email" name="email" placeholder="Email"><br>--}}
{{--        <input type="password" name="password" placeholder="Password"><br>--}}
{{--        <input type="password" name="confirm_password" placeholder="Confirm Password"><br>--}}
{{--        <input type="submit" name="submit" value="Submit">--}}
{{--    </form>--}}
{{--@endsection--}}

@section('content')

    {!! Form::open(array('route' => 'users.store',  'method' => 'POST', 'role' => 'form',  'required' => 'required')) !!}
    <div class="form-group {{$errors->has('username') ? 'is-invalid':''}}">
        {!! Html::decode(Form::label('username', 'User Name'.' <span class="required"> * </span>')) !!}
        {!! Form::text('username',old('username'), array('class' => 'form-control', 'placeholder' => __('site.username'))) !!}
        @if ($errors->has('username'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('username') }}
            </div>
        @endif
    </div>

    <div class="form-group {{$errors->has('email') ? 'is-invalid':''}}">
        {!! Html::decode(Form::label('email', __('site.email').' <span class="required"> * </span>')) !!}
        {!! Form::text('email',old('email'), array('class' => 'form-control', 'placeholder' => __('site.email'))) !!}
        @if ($errors->has('email'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('email') }}
            </div>
        @endif
    </div>

    <div class="form-group {{$errors->has('full_name') ? 'is-invalid':''}}">
        {!! Html::decode(Form::label('full_name', __('site.full_name').' <span class="required"> * </span>')) !!}
        {!! Form::text('full_name',old('username'), array('class' => 'form-control', 'placeholder' => __('site.full_name'))) !!}
        @if ($errors->has('full_name'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('full_name') }}
            </div>
        @endif
    </div>

    <div class="form-group {{$errors->has('nickname') ? 'is-invalid':''}}">
        {!! Html::decode(Form::label('nickname', __('site.nickname').' <span class="required"> * </span>')) !!}
        {!! Form::text('nickname',old('nickname'), array('class' => 'form-control', 'placeholder' => __('site.nickname'))) !!}
        @if ($errors->has('nickname'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('nickname') }}
            </div>
        @endif
    </div>

    <div class="form-group {{$errors->has('password') ? 'is-invalid':''}}">
        {!! Html::decode(Form::label('password', __('site.password').' <span class="required"> * </span>')) !!}
        {!! Form::password('password',array('class' => 'form-control', 'placeholder' => __('site.password'))) !!}
        @if ($errors->has('password'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('password') }}
            </div>
        @endif
    </div>

    <div class="form-group {{$errors->has('password_confirmation') ? 'is-invalid':''}}">
        {!! Form::label('password_confirmation', __('site.confirm_password')) !!}
        {!! Form::password('password_confirmation', array('class' => 'form-control', 'placeholder' =>  __('site.confirm_password'))) !!}
        @if ($errors->has('password_confirmation'))
            <div class="invalid-feedback animated fadeInDown">
                {{ $errors->first('password_confirmation') }}
            </div>
        @endif
    </div>

    {{--    <div class="form-group {{$errors->has('role') ? 'is-invalid':''}}">--}}
    {{--        {!! Html::decode(Form::label('role', __('site.role.role').' <span class="required"> * </span>')) !!}--}}

    {{--        @foreach($roles as $role)--}}
    {{--            <div class="form-check">--}}
    {{--                <label class="custom-checkbox">--}}
    {{--                    {{ Form::checkbox('role[]',$role->id,'',['class'=>'custom-control-input']) }}--}}
    {{--                    <span>{{ $role->display_name }}</span>--}}
    {{--                </label>--}}
    {{--                <br>--}}
    {{--            </div>--}}
    {{--        @endforeach--}}
    {{--        @if ($errors->has('role'))--}}
    {{--            <div class="invalid-feedback animated fadeInDown">--}}
    {{--                {{ $errors->first('role') }}--}}
    {{--            </div>--}}
    {{--        @endif--}}
    {{--    </div>--}}


    <div class="form-group">
        {!! Form::button(__('site.save'), array('class' => 'btn btn-outline-success btn-block','type' => 'submit')) !!}
    </div>
    {!! Form::close() !!}


    {{--    <p>This is my body content.</p>--}}
@endsection

resources/views/backend/users/edit.blade.php
{{ $user->username }}

{!! Form::open(array('route' => ['users.update',$user->id],  'method' => 'PUT', 'role' => 'form',  'required' => 'required')) !!}
<div class="row">
    <div class="col-md-7">
        <div class="form-group row">
            <div class="col-6">
                {!! Form::label('username', __('site.username')) !!}
                {!! Form::text('username',$user->username, array('class' => 'form-control', 'placeholder' => __('site.username'),'disabled' => 'disabled')) !!}
            </div>
            <div class="col-6">
                {!! Form::label('email', __('site.email')) !!}
                {!! Form::text('email',$user->email, array('class' => 'form-control', 'placeholder' => __('site.email'),'disabled' => 'disabled')) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('full_name', __('site.full_name')) !!}
            {!! Form::text('full_name',is_null($user->profile)?null:$user->profile->full_name, array('class' => 'form-control', 'placeholder' => __('site.full_name'))) !!}
        </div>
    </div>
{{--    <div class="col-md-5">--}}
{{--        <div class="form-group row">--}}
{{--            <div class="col-12">--}}
{{--                {!! Html::decode(Form::label('featured_image', __('site.avatar'), ['class' => 'control-label']))  !!}--}}
{{--                <div class="input-group">--}}
{{--                    {{ Form::text('avatar',(!is_null($user->profile) && !is_null($user->profile->avatar))?$user->profile->avatar:Gravatar::src($user->email),['class'=>'form-control', 'id'=>'thumbnail']) }}--}}
{{--                </div>--}}
{{--                <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ (!is_null($user->profile) && !is_null($user->profile->avatar))?$user->profile->avatar:Gravatar::src($user->email) }}">--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
</div>
<div class="row">
    <div class="col-md-7">
        <div class="form-group row">
            <div class="col-12">
                {!! Form::label('display_name', __('site.biographical_info')) !!}
                {{ Form::textarea('description', is_null($user->profile)?null:$user->profile->description, array('class' => 'form-control', 'placeholder' => __('site.user.few_details_about_yourself'))) }}
            </div>
        </div>
    </div>
    <div class="col-md-5">

        <div class="form-group">
            {!! Form::label('nickname', __('site.nickname')) !!}
            {!! Form::text('nickname',is_null($user->profile)?null:$user->profile->nickname, array('class' => 'form-control', 'placeholder' => __('site.nickname'))) !!}
        </div>
        <div class="form-group">
            {!! Form::label('display_name', __('site.display_name')) !!}
            {!! Form::text('display_name',is_null($user->profile)?null:$user->profile->display_name, array('class' => 'form-control', 'placeholder' => __('site.display_name'))) !!}
        </div>

        <div class="form-group">
            {!! Form::label('website',  __('site.user.website_url')) !!}
            {!! Form::text('website',is_null($user->profile)?null:$user->profile->website, array('class' => 'form-control', 'placeholder' => __('site.user.website_url'))) !!}
        </div>

{{--        <div class="form-group {{$errors->has('role') ? 'is-invalid':''}}">--}}
{{--            {!! Html::decode(Form::label('role', __('site.role.role').' <span class="required"> * </span>')) !!}--}}

{{--            @foreach($roles as $role)--}}
{{--                <div class="form-check">--}}
{{--                    <label class="custom-checkbox">--}}
{{--                        {{ Form::checkbox('role[]',$role->id,in_array($role->id, $user->roles()->pluck('id')->toArray()),['class'=>'custom-control-input']) }}--}}
{{--                        <span>{{ $role->display_name }}</span>--}}
{{--                    </label>--}}
{{--                </div>--}}
{{--            @endforeach--}}
{{--            @if ($errors->has('role'))--}}
{{--                <div class="invalid-feedback animated fadeInDown">--}}
{{--                    {{ $errors->first('role') }}--}}
{{--                </div>--}}
{{--            @endif--}}
        </div>
    </div>


</div>
<div class="form-group row">
    <div class="col-12">
        <button type="submit" class="btn btn-outline-success">
            <i class="fa fa-check"></i> {{ __('site.save') }}
        </button>
    </div>
</div>

{!! Form::close() !!}

resources/views/backend/users/index.blade.php
@extends('backend.layout')
@section('title'){{ __('Users') }} @endsection
@section('content')
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">User Nav</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Users</li>
            </ol>
            <div class="card mb-4">
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>username</th>
                                <th>Roles</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->username}}</td>
                                <td>{{$user->getRoleNames()}}</td>
                                {{-- <td>{{$user->hasRole('admin')}}</td>--}}
                                <td><a href="#" class="btn btn-info">Edit</a> <a href="#" class="btn btn-light">Delete</a></td>
                            </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div style="height: 100vh;"></div>
        </div>
    </main>
@endsection

resources/views/backend/users/sidebar.blade.php
<?php